### PR TITLE
Update readme

### LINKED ISSUE #43: Update README
Must-haves:
- Project overview
- Features list
- Instructions for local development (yarn, yarn start, yarn test, husky local CI setup explained)
- Technologies used (You can use badges for this)
- Team members profiles (links to github profiles)
- Link to hosted project (add after hosting is done)

Nice to haves:
- Screenshots of your system diagrams, ERD diagram, home page

For more details, check out [this article](https://dev.to/coderarchive/writing-a-high-quality-readme-1k3j).
[Here](https://github.com/ReCoded-Org/capstone-turkey-love-thy-neighbour#readme) is an example README from a frontend capstone project.

### PR DESCRIPTION
**Pull request by mehmetfatiherdem**
closes #43

### CODE REVIEW

**Comment by mehmetfatiherdem** [comment]
Hey @Shrreya I think we tried to push at the same time :D well I just wanted to add the live demo and then saw some duplicate sections I was going to remove them.

**Comment by Shrreya** [comment]
> Hey @Shrreya I think we tried to push at the same time :D well I just wanted to add the live demo and then saw some duplicate sections I was going to remove them.

Oops, so sorry I should have informed you first. Anyway it's all done now. So we can merge the PR.

**Review by Shrreya — APPROVED** [review]

**Review by AmmarBaki2 — APPROVED** [review]

**Comment by mehmetfatiherdem** [comment]
let's add demo link to View Demo too

**Comment by mehmetfatiherdem** [comment]
@Shrreya can you add the demo link?

**Comment by Shrreya** [comment]
> @Shrreya can you add the demo link?

Done!

**Comment by mehmetfatiherdem** [comment]
> > @Shrreya can you add the demo link?
> 
> Done!

Thank you very much :pray:

**Pull request merged**
